### PR TITLE
Adds moment.js, fixes lingering events, and adds Yarn lockfile

### LINKED ISSUE #19: The last day/event on the calendar remains several days later
This might be due to the active event function. It's not all that important however, as the splash is usually tucked away neatly when the last day is over anyways.

### PR DESCRIPTION
**Pull request by plusk**
Primary objective here was to fix #19, which this pull request absolutely does. In doing so I shortened down the logic for `getActiveEvent` in the Calendar component, as it was covering an "edge case" that no longer exists. 
In the process I also added [Moment.js](https://momentjs.com/), which _significantly_ simplifies our date formatting, and makes the code far more legible. No more `new Date`!
Oh, and I added the auto-generated lockfile for Yarn too.

### CODE REVIEW

**Comment by plusk** [comment]
One thing to look out for on code review that I'm unsure of is the everlasting timezone debacle. I _think_ Moment fixes the issue we were having back then, but it's hard to test out. The problem back then (#15) was the difference of the timezone used to create the `TODAY` constant and the event dates, which were compared against each other. Again, I think moment handles this, but some confirmation would be handy.

File: components/calendar/day.js [hunk 1]
```diff
@@ -1,18 +1,15 @@
 import Event from './event';
+import moment from 'moment';
 
-const DAY_NAMES = [  'Søndag', 'Mandag', 'Tirsdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lørdag' ];
-const MONTH_NAMES = [ 'januar', 'februar', 'mars', 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'desember' ];
+moment.locale('nb')
```
Comment (duvholt) [inline components/calendar/day.js]: Move this to the entry script (index.js). Right now I think moment might behave different if other modules are loaded before day.js. Not entirely sure tho.

File: components/calendar/day.js [hunk 2]
```diff
@@ -1,18 +1,15 @@
 import Event from './event';
+import moment from 'moment';
 
-const DAY_NAMES = [  'Søndag', 'Mandag', 'Tirsdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lørdag' ];
-const MONTH_NAMES = [ 'januar', 'februar', 'mars', 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'desember' ];
```
Comment (duvholt) [inline components/calendar/day.js:4]: 👌

File: components/calendar/index.js [hunk 3]
```diff
@@ -64,60 +58,70 @@ const Calendar = React.createClass({
...
+      if (currentEventDate.isAfter(previousEventDate, 'day')) {
+        if (previousEventDate.isBefore(TODAY, 'day')) {
+          preDays.push(
+            <Day events={daysEvents} active={this.state.active} eventClickHandler={this.eventClickHandler} key={id}/>
+          );
         }
         else {
-	  let active = getActiveEvent(postDays, daysEvents, this.state.active);
-          postDays.push(<Day events={daysEvents} active={active} eventClickHandler={this.eventClickHandler} key={id}/>);
+          let active = getActiveEvent(postDays, this.state.active);
```
Comment (duvholt) [inline components/calendar/index.js]: nitpick: I think this can be const.

File: components/calendar/index.js [hunk 4]
```diff
@@ -64,60 +58,70 @@ const Calendar = React.createClass({
...
 
     let preDays = [];
     let postDays = [];
     let preDaysSection = '';
 
     events.forEach(function (event, index) {
-      event.start_time = new Date(event.start_time);
-      event.end_time = new Date(event.end_time);
       event.index = index;
+      let currentEventDate = moment(event.start_time)
```
Comment (duvholt) [inline components/calendar/index.js]: nitpick: I think this can be const.

File: components/calendar/index.js [hunk 5]
```diff
@@ -64,60 +58,70 @@ const Calendar = React.createClass({
...
     let id = 0;
-    let lastEpochDays = 0;
     let daysEvents = [];
+    let previousEventDate;
 
     let preDays = [];
     let postDays = [];
     let preDaysSection = '';
 
     events.forEach(function (event, index) {
```
Comment (duvholt) [inline components/calendar/index.js:68]: Maybe a bit out of scope for this pr, but I think this function should be split into smaller functions. Both to reduce duplicate code and to make it clearer what each section actually does.

File: components/calendar/index.js [hunk 6]
```diff
@@ -64,60 +58,70 @@ const Calendar = React.createClass({
...
-	</div>
+        <div className="cal-section--preDays">
+          { preDays }
+        </div>
       );
     }
     else if (preDays.length > 0 && !this.state.preDaysSectionActive) {
       preDaysSection = (
-	<button className="cal-button--preDays" onClick={this.preDaysClickHandler}>Vis tidligere arrangementer</button>
+	      <button className="cal-button--preDays" onClick={this.preDaysClickHandler}>Vis tidligere arrangementer</button>
```
Comment (duvholt) [inline components/calendar/index.js]: Mixing of tabs and spaces! 😮

**Review by duvholt — CHANGES_REQUESTED** [review]
Good shit. Made some nitpicky comments as I learned to not do while code reviewing. :^)

**Comment by duvholt** [comment]
```
> moment().utc()
moment.utc("2017-06-29T19:23:26.153+00:00")
> moment('2017-06-29 21:23:00').utc()
moment.utc("2017-06-29T19:23:00.000+00:00")
```

Timezone bug should be fixed with moment.

File: components/calendar/day.js (hunk 1 above)
Comment (plusk) [reply components/calendar/day.js]: Mind elaborating on this? I'm importing moment in every component it's used, importing it only in in the parent doesn't seem to work from my testing. I will move that line in particular to the index of the Calendar component however. Setting the locale once there works, so there's no point in setting it to the same value for every Day (of which we have about 14 of typically),

File: components/calendar/index.js (hunk 5 above)
Comment (plusk) [reply components/calendar/index.js:68]: I'll definitely look into this while dealing with the other issues, and failing that I'll do it independent of issues later.

File: components/calendar/index.js [hunk 7]
```diff
@@ -7,7 +7,9 @@ import { API_EVENTS_URL } from '../../common/constants';
 require('es6-promise').polyfill();
 require('isomorphic-fetch');
 
-const TODAY = moment()
+moment.locale('nb');
```
Comment (duvholt) [inline components/calendar/index.js]: I meant index.js in the root folder. 😛 
I usually use the main file to configure things like moment. This way it's easy to find later on instead of being buried in a "random" file.

Comment (plusk) [reply components/calendar/index.js]: Sure, fixed that now. Seems a bit weird to import moment to the index at root just to set locale, but sure.

**Review by duvholt — APPROVED** [review]
